version: '3.7'
services: 
  dev:
    build:
        context: .
        dockerfile: Dockerfile-dev
    ports:
      - "8080:8080"
    volumes: 
      - "./app:/usr/src/app"
    network_mode: "host"
    working_dir: /usr/src/app
    user: mountuser
    command: [ "npm", "start" ]