FROM node:alpine as builder

WORKDIR /app

COPY app/package*.json ./
RUN npm install
COPY app ./
RUN npm run build

FROM nginx:alpine

COPY ./nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/build /usr/share/nginx/html
